# Job to run a Ray program in its own pod. Assumes that a Ray cluster is already
# running.
apiVersion: batch/v1
kind: Job
metadata:
  generateName: ray-test-job-
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: jupyterhub
      containers:
        - name: ray
          image: rayproject/ray:nightly
          volumeMounts:
          - mountPath: /efs
            name: efs-volume
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "wget https://gist.githubusercontent.com/yinweisu/39e18a73105f0190e0e5f057273d60b5/raw/e738771f206eb226b1204fdc9431e7ee535a1e1d/job_example.py -O job_example.py && python job_example.py"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
